### PR TITLE
Add structure for To Do List project

### PR DESCRIPTION
**Pull request by shakerAbuDrais**
I have created a new repo and added the following to it: 

1- added and configured wepback required files and configurations 
2- added index.html, index.js, and style.css to src dir in my project
3- built and tested the structure for the todo list project.

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @shakerAbuDrais 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

####  Required Changes :recycle:
Please check if you are using the right configuration for setting up the linters on the javascript module to fix the liter errors.

#### Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
##### Please, remember to tag me in your question so I can receive the notification.
##### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

**Review by Lameck1 — COMMENTED** [review]
Hello @shakerAbuDrais,

You've done well working on the linter issues.

The next review on this PR will be more like a first review. If changes are requested on this PR, please go ahead and work on them. In the previous instance, your Code Review Request was supposed to be invalidated because of the failing linter checks. The next review is the one that will be considered as the first review on this PR.

Cheers and happy coding 🎉.

**Comment by shakerAbuDrais** [comment]
hey @Lameck1 thank you for the insights, I have requested a new R before you leave this comment are you the reviewer?

**Comment by Lameck1** [comment]
@shakerAbuDrais, I am the Senior Code Reviewer. There is another reviewer working on this PR already.

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @shakerAbuDrais, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Linters are correctly setup :heavy_check_mark: 
- Good commits history :heavy_check_mark: 

## Required Changes ♻️
#### PLEASE FOLLOW THE COMMENT BELOW :arrow_down: BECAUSE I CAN NOT USE INLINE COMMENTS :smile: 
- [ ] Please make sure that in your index.html file and write your HTML your create empty To Do List placeholder with <div> or <ul> element to follow the requirement :+1: 

- [ ] Good job so far great project implementation :clap: But when I change the index value the list order is not affected according to the project requirement  **On page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.** Please fix it :smile: 

- [ ] Good job with your project design :+1:  But please make sure that you follow the wireframe as required for this project. Your design is a bit different :cry:  Please fix it because it is very important as a developer to follow the project design guidelines :smile:

#### Your design
Screenshot from 2022-09-28 13-19-05

#### Project wireframe
Screenshot from 2022-09-28 13-18-50

 

_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by 1GORDON — APPROVED** [review]
# Status: APPROVED 🟢 

Hi @shakerAbuDrais 👏

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
